### ISSUE TITLE
upgrade to HTTP Basic Access Authentication

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rgithub#1]
GitHub is warning us of a "Deprecation notice for authentication via URL query parameters"

> Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated and will be removed July 1st, 2020.
> Depending on your API usage, we'll be sending you this email reminder once every 3 days.
> Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

I took a very quick look and it looks like the offending line is here:

https://github.com/att/rgithub/blob/04c5d13cb8a9ea6723641f2c09504640ff9d69b2/R/github.R#L195

I tried some dumb stuff to prepend an `Authorization:` header to the body instead, [as described here](https://en.wikipedia.org/wiki/Basic_access_authentication#Protocol):

```r
  if (!is.null(ctx$token))
    body <- paste(paste("Authorization:", "Basic", base64encode(ctx$token)), body, sep='\n')
```

but I got "Invalid token, could not authenticate with the back-end".

I guess I am confused about how we are supposed to use Basic Authentication, which usually takes a username and password, with just an access token. Anyway, I thought I'd file the issue since we've got about 4-5 months before we won't be able to use GitHub OAuth anymore.

(@s-u, I've forked your repo here and enabled issues, since cscheid has [abandoned](https://github.com/cscheid/rgithub/issues/70) the original.)

**Comment by s-u** [comment]
The above commit should fix it - it worked for me but I'd rather have it independently confirmed.

**Comment by s-u** [comment]
For posterity, the GitHub references are confusing and talk about unrelated things (this has nothing to do with the basic authentication nor personal tokens which is what the error points to), but the relevant document is [web application flow](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow)

**Comment by gordonwoodhull** [comment]
Aha, yes I was wondering what the heck they were talking about. That ref actually sort of makes sense!

Thanks @s-u, I will test this tomorrow.

**Comment by gordonwoodhull** [comment]
Confirmed. Thanks @s-u, and I'm glad to see the clean `add_headers(...)` method.
